DROP TABLE item;

CREATE TABLE item (
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name         VARCHAR2(100) NOT NULL,
    price        NUMBER(10, 2) NOT NULL,
    total_number NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO item (name, price, total_number)
VALUES ('Laptop', 25000, 5);

INSERT INTO item (name, price, total_number)
VALUES ('Mouse', 350, 20);

COMMIT;

SELECT * FROM item;
