SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 100 AND 105;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN(151 , 152, 153, 154 , 155);

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'P%'OR  FIRST_NAME LIKE  'p%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%A'OR  FIRST_NAME LIKE  '%a';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%A%'OR  FIRST_NAME LIKE  '%a%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '__E%'OR  FIRST_NAME LIKE  '__e%';

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

INSERT INTO EMPLOYEES 
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES 
(222, 'Dina', 'Elmowafy', 'elmowafyd', '2011120212122', SYSDATE, 'AD_ASST', 35000, NULL, NULL, 100);

SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE 'AD_VP' OR JOB_ID LIKE 'IT_PROG';

SELECT * FROM EMPLOYEES ORDER BY LAST_NAME  ASC;

SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE  DESC ;

SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID  ASC , SALARY DESC;

SELECT LOWER(LAST_NAME) AS LAST_NAME_LOWER FROM EMPLOYEES ;

SELECT UPPER(FIRST_NAME) AS FIRST_NAME_UPPER FROM EMPLOYEES ;

SELECT  INITCAP(FIRST_NAME) AS FIRST_NAME, INITCAP(LAST_NAME) AS LAST_NAME,  EMPLOYEES.*FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE LOWER(LAST_NAME) = 'smith';



