CREATE TABLE MANAGER(
id NUMBER,
name VARCHAR2(20),
age NUMBER,
birth_date DATE,
address VARCHAR2(100)
);

ALTER TABLE MANAGER
DROP COLUMN address;

ALTER TABLE MANAGER 
ADD (
    city_address VARCHAR2(50),
    street VARCHAR2(50)
);

ALTER TABLE MANAGER
RENAME COLUMN name TO full_name;

ALTER TABLE MANAGER  READ ONLY;

CREATE TABLE OWNER AS SELECT id,full_name,birth_date FROM MANAGER WHERE 1=0;

RENAME MANAGER TO MASTER;

DROP TABLE MASTER;
DROP TABLE OWNER;
